"""
Константы и пути к ресурсам для TheFastestCar.
"""

WIDTH, HEIGHT = 1280, 720
FPS = 60

ASSETS_PATH = "assets/"
ASSETS = {
    "road": ASSETS_PATH + "road_background.png",
    "player": ASSETS_PATH + "car_player.png",
    "enemy": ASSETS_PATH + "enemy_player.png",
    "fire": ASSETS_PATH + "fire.png",
}

# Player settings
PLAYER_ROTATION = 90
PLAYER_SCALE_W = 0.3
PLAYER_SCALE_H = 0.5
PLAYER_START_X_OFFSET = -90
PLAYER_START_Y_MARGIN = 20
PLAYER_MAX_HEALTH = 100
PLAYER_HITBOX_W = 0.7
PLAYER_HITBOX_H = 0.6
PLAYER_MOVE_STEP = 10
PLAYER_SIDE_MARGIN = 20

# Enemy settings
ENEMY_IMAGE_SCALE_W = 0.15
ENEMY_IMAGE_SCALE_H = 0.25
ENEMY_SPEED_CHANGE_MIN = 600
ENEMY_SPEED_CHANGE_MAX = 1500
ENEMY_DRIFT_CHANGE_MIN = 250
ENEMY_DRIFT_CHANGE_MAX = 700
ENEMY_DRIFT_MULT_MIN = 0.4
ENEMY_DRIFT_MULT_MAX = 1.0
ENEMY_HITBOX_W = 0.8
ENEMY_HITBOX_H = 0.85
ENEMY_BASE_DAMAGE_OFFSET = 8
ENEMY_DAMAGE_STD_RATIO = 0.15
ENEMY_DAMAGE_CLAMP_MULT = 2.0
ENEMY_DEFAULT_SPEED = 5
ENEMY_SPEED_TARGET_MIN = -0.3
ENEMY_SPEED_TARGET_MAX = 0.3
ENEMY_SPEED_VARIATION_SMOOTH = 0.12
ENEMY_DRIFT_SMOOTH = 0.25

# Bonus settings
BONUS_SIZE = 34
BONUS_COLOR = (255, 215, 0)
BONUS_OUTLINE_COLOR = (255, 245, 180)
BONUS_SCORE_BASE = 5
BONUS_HEAL_MEAN = 20.0
BONUS_HEAL_STD = 5.0
BONUS_HEAL_MIN = 5
BONUS_HEAL_MAX = 40

# Floating text
FLOATING_TEXT_LIFESPAN = 900
FLOATING_TEXT_RISE = 36
FLOATING_TEXT_COLOR = (255, 255, 255)

# Road
ROAD_HALF_WIDTH_MARGIN = 450
ROAD_SPEED = 5

# Spawn / lanes
SPAWN_LEFT_SAFE_OFFSET = 140
SPAWN_RIGHT_SAFE_OFFSET = 220
LANE_COUNT = 5

# Spawn intervals
BASE_SPAWN_INTERVAL = 2200
MIN_SPAWN_INTERVAL = 700
BASE_BONUS_INTERVAL = 3600
MIN_BONUS_INTERVAL = 1400

# Evolution / GA
EVOLUTION_INTERVAL = 10
GA_POPULATION_SIZE = 8
GA_MUTATION_RATE = 0.35

# Speed / throttle
PLAYER_START_SPEED = 2
PLAYER_MAX_SPEED = 15
PLAYER_MIN_SPEED = 2
SPEED_ACCELERATION = 0.07
SPEED_COAST_DECELERATION = 0.03
SPEED_BRAKE_DECELERATION = 0.3
SPEED_SMOOTHING = 0.08
THROTTLE_UP_RATE = 0.02
THROTTLE_COAST_RATE = 0.008
THROTTLE_BRAKE_RATE = 0.05
MAX_LIFT = 36
LIFT_SMOOTHING = 0.08
COAST_SMOOTHING = 0.035
BRAKE_SMOOTHING = 0.18

# Display
SPEED_DISPLAY_MULT = 7

# UI
UI_FONT_SIZE = 36
UI_SCORE_POS = (10, 10)
UI_BEST_SCORE_POS = (10, 35)
UI_HEALTH_BAR = (10, 70, 220, 14)
UI_HEALTH_BG_COLOR = (60, 60, 60)
UI_HEALTH_COLOR = (50, 205, 50)
UI_SPEED_POS = (10, HEIGHT - 30)

# UI text and background
UI_TEXT_COLOR = (255, 255, 255)
BACKGROUND_COLOR = (0, 0, 0)

# Floating text offsets for common messages
FLOATING_TEXT_OFFSET_HIT = 56
FLOATING_TEXT_OFFSET_HEAL = 72
FLOATING_TEXT_OFFSET_SCORE = 44

# Misc
FIRE_SCALE = 0.5
CRASH_DISPLAY_DELAY = 120
ENEMY_MIN_GAP = 12
